service: test-stack-1-test-2

frameworkVersion: '3'

custom:
  stackName: test-stack-1
  baseName: ${self:custom.stackName}-test_2

provider:
  name: aws
  runtime: python3.9
  environment: ${file(../setup/${opt:stage, 'dev'}/env_variables.json)}

package:
  individually: true
  patterns:
    - '!resources/*.yml'

functions:
  test_2:
    handler: test_2.lambda_handler
    name: ${self:custom.baseName}

