custom:
  bucket: ${param:bucket, "serverless-stack-deployments"}
  pythonRequirements:
    dockerizePip: non-linux
  runtime: ${param:runtime, "python3.9"}
  scriptHooks:
    before:package:createDeploymentArtifacts: []
frameworkVersion: '3'
functions: []
package:
  excludeDevDependencies: true
  individually: true
plugins:
- serverless-deployment-bucket
- serverless-python-requirements
- serverless-scriptable-plugin
provider:
  deploymentBucket:
    name: ${self:custom.bucket}
  name: aws
  region: ${file(setup/stage/${opt:stage, "dev"}.json):REGION, "sa-east-1"}
  runtime: ${self:custom.runtime}
resources: []
service: test-stack-delete-message
