custom:
  bucket: ${param:bucket, "serverless-stack-deployments"}
  pythonRequirements:
    dockerizePip: non-linux
  runtime: ${param:runtime, "python3.9"}
  scriptHooks:
    before:package:createDeploymentArtifacts:
    - rm -rf .serverless/services/hola/core/requirements/*.dist-info
    - rm -rf .serverless/services/hola/core/requirements/*.egg-info
    - rm -rf .serverless/services/hola/core/requirements/requirements*
    - rm -rf .serverless/services/como/core/requirements/*.dist-info
    - rm -rf .serverless/services/como/core/requirements/*.egg-info
    - rm -rf .serverless/services/como/core/requirements/requirements*
    - rm -rf .serverless/services/estas/core/requirements/*.dist-info
    - rm -rf .serverless/services/estas/core/requirements/*.egg-info
    - rm -rf .serverless/services/estas/core/requirements/requirements*
frameworkVersion: '3'
functions:
- ${file(services/hola/event.yml)}
- ${file(services/como/event.yml)}
- ${file(services/estas/event.yml)}
package:
  excludeDevDependencies: true
  individually: true
plugins:
- serverless-deployment-bucket
- serverless-python-requirements
- serverless-scriptable-plugin
provider:
  deploymentBucket:
    name: ${self:custom.bucket}
  name: aws
  region: ${file(setup/stage/${opt:stage, "dev"}.json):REGION, "sa-east-1"}
  runtime: ${self:custom.runtime}
resources: []
service: test-stack-ci
