name: Test CI
on:
  pull_request:
    branches:
     - dev

jobs:
  run-unit-tests:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Test file
       run: |
          python stack_project/services/lambda_1/core/controllers/test_formatted_name.py
  
    