name: Test CI
on:
  pull_request:
    branches:
     - dev
     - release
     - prod

jobs:
  run-unit-tests:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Test file
       run: |
          python stack_project_1/services/project_1/lambda_1/test_name_function.py
  
    