name: Test CI
on:
  push:
    branches:
    - dev
    - release
    - main
  pull_request:
    branches:
    - dev
    - release
    - main
  
jobs:
  run-unit-tests:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Test file
       run: |
          python stack_project/services/lambda_1/core/controllers/test_formatted_name.py

  send-slack-message:
    runs-on: ubuntu-latest
    needs: ["run-unit-tests"]
    if: github.event_name == 'pull_request'
    steps:
      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
<<<<<<< HEAD
          SLACK_MESSAGE: 'Ready to merge'

  
  send-slack-message:
    runs-on: ubuntu-latest
    needs: ["run-unit-tests"]
    if: github.event_name == 'pull_request'
    steps:
      - name: send a slack message
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Ready to merge'
  
=======
          SLACK_MESSAGE: 'Ready to merge'  
>>>>>>> 225aae2d3ac33ea5609a3808838b28e86620dea2
    