name: Test CI
on:
  pull_request:
    branches:
     - dev
     - release
     - prod
     - crafting

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test PR
        run: |
          echo ${{ github.event.pull_request }} | jq
  # send-slack-message:
  #   runs-on: ubuntu-latest
  #   needs: ["deploy"]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: send a slack message
  #       uses: ./.github/actions/slack
  #       with:
  #         slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
  #         message: Despliegue realizado correctamente
  #         title: Despliegue
  # run-unit-tests:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v1
  #    - name: Test file
  #      run: |
  #         python stack_project_1/services/project_1/lambda_1/test_name_function.py
  
    