name: Test CI
on:
  pull_request:
    branches:
     - dev
     - release
     - prod
     - crafting

jobs:
  get-pr-link:
    runs-on: ubuntu-latest
    outputs:
      link: ${{ steps.get-link-pr.outputs.link }}      
    steps:
      - name: test PR
        id: get-link-pr
        run: |
          LINK="https://github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}"
          echo "::set-output name=link::$( echo "$LINK" )"          
  send-slack-message:
    runs-on: ubuntu-latest
    needs: ["get-pr-link"]
    steps:
      - uses: actions/checkout@v2
      - name: send a slack message
        uses: ./.github/actions/slack
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          title: ":pr: Creación de PR para CR"
          message: "Se ha creado el <${{ needs.get-pr-link.outputs.link }}|siguiente> PR"
  # run-unit-tests:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v1
  #    - name: Test file
  #      run: |
  #         python stack_project_1/services/project_1/lambda_1/test_name_function.py
  

    