name: Test CI
on:
  pull_request:
    branches:
     - dev
     - release
     - prod
     - crafting

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      link: ${{ steps.get-link-pr.outputs.link }}      
    steps:
      - name: test PR
        id: get-link-pr
        run: |
          echo "HOME ${HOME}"
          echo "GITHUB_WORKFLOW ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA ${GITHUB_SHA}"
          echo "GITHUB_REF ${GITHUB_REF}"
          echo "PR NUMBER ${{ github.event.number }}"
          LINK="https://github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}"
          echo "::set-output name=link::$( echo "$LINK" )"          
  send-slack-message:
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - uses: actions/checkout@v2
      - name: send a slack message
        uses: ./.github/actions/slack
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: ${{ needs.test.outputs.link }}
          title: Despliegue
  # run-unit-tests:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v1
  #    - name: Test file
  #      run: |
  #         python stack_project_1/services/project_1/lambda_1/test_name_function.py
  

    